// Lifestyle / PC products filling the PC & Laptop, Gaming Chair,
// Controller and Mouse Pad categories. Images resolve to real photos
// under /uploads/products/<slug>.jpg (see scripts/add-lifestyle-products.js).

const img = (name) =>
  `/uploads/products/${name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")}.jpg`;

const lifestyleProducts = [
  // ——— Gaming PC ———
  {
    name: "Alienware Aurora R16 Gaming PC",
    category: "Gaming PC",
    brand: "Alienware",
    price: 2199.99,
    discount: 10,
    stock: 7,
    rating: 4.7,
    numReviews: 156,
    tags: ["gaming-pc", "alienware", "desktop", "rtx"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "High-performance pre-built gaming desktop with a 14th-gen Intel CPU and RTX graphics, ready for 4K play.",
    image: "/uploads/products/alienware-aurora-r16-gaming-pc.png",
    specs: {
      cpu: "Intel Core i7-14700F",
      gpu: "NVIDIA RTX 4070",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
    },
  },
  {
    name: "CyberPowerPC Gamer Xtreme VR",
    category: "Gaming PC",
    brand: "CyberPowerPC",
    price: 1349.99,
    discount: 15,
    stock: 10,
    rating: 4.5,
    numReviews: 284,
    tags: ["gaming-pc", "cyberpowerpc", "desktop", "vr"],
    isFeatured: false,
    isTopSelling: true,
    description:
      "VR-ready pre-built gaming tower with liquid cooling, RGB lighting and a spacious tempered-glass case.",
    image: img("CyberPowerPC Gamer Xtreme VR"),
    specs: {
      cpu: "Intel Core i5-14400F",
      gpu: "NVIDIA RTX 4060",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
    },
  },
  {
    name: "iBUYPOWER SlateMesh Gaming PC",
    category: "Gaming PC",
    brand: "iBUYPOWER",
    price: 1099.99,
    discount: 0,
    stock: 12,
    rating: 4.4,
    numReviews: 198,
    tags: ["gaming-pc", "ibuypower", "desktop", "esports"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Mesh-front mid-tower esports desktop built for FPS titles at high frame rates out of the box.",
    image: "/uploads/products/ibuypower-slatemesh-gaming-pc.png",
    specs: {
      cpu: "AMD Ryzen 5 7600",
      gpu: "NVIDIA RTX 4060",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
    },
  },

  // ——— Office PC ———
  {
    name: "Dell Inspiron Desktop 3020",
    category: "Office PC",
    brand: "Dell",
    price: 649.99,
    discount: 5,
    stock: 15,
    rating: 4.3,
    numReviews: 187,
    tags: ["office-pc", "dell", "desktop", "productivity"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Compact and quiet desktop for everyday office work, web apps and multitasking.",
    image: img("Dell Inspiron Desktop 3020"),
    specs: {
      cpu: "Intel Core i5-13400",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      os: "Windows 11 Home",
    },
  },
  {
    name: "HP Pavilion Tower 670",
    category: "Office PC",
    brand: "HP",
    price: 549.99,
    discount: 0,
    stock: 18,
    rating: 4.2,
    numReviews: 143,
    tags: ["office-pc", "hp", "desktop", "productivity"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Reliable tower PC with modern I/O for home offices, schools and small businesses.",
    image: img("HP Pavilion Tower 670"),
    specs: {
      cpu: "AMD Ryzen 5 5500",
      ram: "16GB DDR4",
      storage: "512GB NVMe SSD",
      os: "Windows 11 Home",
    },
  },

  // ——— Gaming Laptop ———
  {
    name: "ASUS ROG Strix G16",
    category: "Gaming Laptop",
    brand: "ASUS",
    price: 1799.99,
    discount: 12,
    stock: 8,
    rating: 4.7,
    numReviews: 321,
    tags: ["gaming-laptop", "asus", "rog", "rtx"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "16-inch 165Hz ROG Strix with a 13th-gen Intel CPU and RTX graphics on the go.",
    image: img("ASUS ROG Strix G16"),
    specs: {
      display: "16\" 165Hz QHD+",
      cpu: "Intel Core i7-13650HX",
      gpu: "RTX 4060 8GB",
      ram: "16GB DDR5",
      storage: "1TB NVMe SSD",
    },
  },
  {
    name: "Razer Blade 16",
    category: "Gaming Laptop",
    brand: "Razer",
    price: 3099.99,
    discount: 8,
    stock: 5,
    rating: 4.6,
    numReviews: 174,
    tags: ["gaming-laptop", "razer", "blade", "premium"],
    isFeatured: true,
    isTopSelling: false,
    description:
      "CNC-milled aluminum gaming laptop with a dual-mode Mini LED display and RTX 4080 power.",
    image: img("Razer Blade 16"),
    specs: {
      display: "16\" Dual-Mode Mini LED",
      cpu: "Intel Core i9-14900HX",
      gpu: "RTX 4080 12GB",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
    },
  },
  {
    name: "Lenovo Legion 5 Pro",
    category: "Gaming Laptop",
    brand: "Lenovo",
    price: 1549.99,
    discount: 10,
    stock: 9,
    rating: 4.5,
    numReviews: 267,
    tags: ["gaming-laptop", "lenovo", "legion", "amd"],
    isFeatured: false,
    isTopSelling: true,
    description:
      "16-inch 165Hz Legion with AMD Ryzen 9 and RTX graphics, tuned for esports and AAA titles.",
    image: img("Lenovo Legion 5 Pro"),
    specs: {
      display: "16\" 165Hz WQXGA",
      cpu: "AMD Ryzen 9 7945HX",
      gpu: "RTX 4070 8GB",
      ram: "32GB DDR5",
      storage: "1TB NVMe SSD",
    },
  },

  // ——— Workstation ———
  {
    name: "Lenovo ThinkStation P3",
    category: "Workstation",
    brand: "Lenovo",
    price: 1899.99,
    discount: 0,
    stock: 4,
    rating: 4.8,
    numReviews: 92,
    tags: ["workstation", "lenovo", "thinkstation", "isv"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "ISV-certified workstation for CAD, rendering and heavy compute with optional pro graphics.",
    image: img("Lenovo ThinkStation P3"),
    specs: {
      cpu: "Intel Xeon W3-2425",
      gpu: "NVIDIA T1000 8GB",
      ram: "32GB ECC DDR5",
      storage: "1TB NVMe SSD",
    },
  },
  {
    name: "Dell Precision 3680 Tower",
    category: "Workstation",
    brand: "Dell",
    price: 2349.99,
    discount: 0,
    stock: 3,
    rating: 4.7,
    numReviews: 74,
    tags: ["workstation", "dell", "precision", "isv"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Reliable tower workstation with professional graphics and certifications for creator workflows.",
    image: img("Dell Precision 3680 Tower"),
    specs: {
      cpu: "Intel Core i9-14900K",
      gpu: "NVIDIA RTX 4000 20GB",
      ram: "64GB DDR5",
      storage: "1TB NVMe SSD",
    },
  },

  // ——— Gaming Chair ———
  {
    name: "Secretlab Titan Evo 2022",
    category: "Gaming Chair",
    brand: "Secretlab",
    price: 549.99,
    discount: 15,
    stock: 11,
    rating: 4.8,
    numReviews: 512,
    tags: ["gaming-chair", "secretlab", "ergonomic"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "Award-winning ergonomic gaming chair with 4D armrests, full recline and cold-cure foam.",
    image: img("Secretlab Titan Evo 2022"),
    specs: {
      material: "SoftWeave Plus / NEO Hybrid",
      adjustable: "4D armrests, lumbar",
      recline: "165°",
      weightLimit: "130kg",
    },
  },
  {
    name: "DXRacer Master Series Gaming Chair",
    category: "Gaming Chair",
    brand: "DXRacer",
    price: 329.99,
    discount: 10,
    stock: 14,
    rating: 4.4,
    numReviews: 236,
    tags: ["gaming-chair", "dxracer", "racing"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Racing-style gaming chair with steel frame, adjustable lumbar support and premium PU leather.",
    image: img("DXRacer Master Series Gaming Chair"),
    specs: {
      material: "PU leather",
      adjustable: "4D armrests, lumbar",
      recline: "155°",
      weightLimit: "120kg",
    },
  },
  {
    name: "RESPAWN 200 Racing Gaming Chair",
    category: "Gaming Chair",
    brand: "RESPAWN",
    price: 199.99,
    discount: 0,
    stock: 20,
    rating: 4.3,
    numReviews: 344,
    tags: ["gaming-chair", "respawn", "racing"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Budget-friendly racing chair with adjustable arms, recline and a headrest pillow.",
    image: img("RESPAWN 200 Racing Gaming Chair"),
    specs: {
      material: "Faux leather",
      adjustable: "2D armrests",
      recline: "135°",
      weightLimit: "113kg",
    },
  },

  // ——— Controller ———
  {
    name: "Xbox Wireless Controller - Carbon Black",
    category: "Controller",
    brand: "Microsoft",
    price: 59.99,
    discount: 0,
    stock: 60,
    rating: 4.7,
    numReviews: 1289,
    tags: ["controller", "xbox", "microsoft", "wireless"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "Iconic wireless controller with textured grips, hybrid D-pad and Bluetooth support.",
    image: img("Xbox Wireless Controller - Carbon Black"),
    specs: {
      platform: "Xbox / PC",
      connectivity: "Xbox Wireless, Bluetooth",
      battery: "2x AA",
      features: "Share button, textured grip",
    },
  },
  {
    name: "Sony DualSense Wireless Controller",
    category: "Controller",
    brand: "Sony",
    price: 69.99,
    discount: 5,
    stock: 48,
    rating: 4.8,
    numReviews: 973,
    tags: ["controller", "sony", "dualsense", "haptic"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "PS5 controller with haptic feedback, adaptive triggers and a built-in microphone.",
    image: img("Sony DualSense Wireless Controller"),
    specs: {
      platform: "PS5 / PC",
      connectivity: "Bluetooth, USB-C",
      battery: "Built-in rechargeable",
      features: "Haptics, adaptive triggers",
    },
  },
  {
    name: "Nintendo Switch Pro Controller",
    category: "Controller",
    brand: "Nintendo",
    price: 69.99,
    discount: 0,
    stock: 35,
    rating: 4.6,
    numReviews: 612,
    tags: ["controller", "nintendo", "switch", "wireless"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Premium wireless controller with HD rumble, motion controls and 40-hour battery life.",
    image: img("Nintendo Switch Pro Controller"),
    specs: {
      platform: "Switch / PC",
      connectivity: "Bluetooth, USB-C",
      battery: "Up to 40 hours",
      features: "HD Rumble, Gyro",
    },
  },
  {
    name: "8BitDo Pro 2 Bluetooth Controller",
    category: "Controller",
    brand: "8BitDo",
    price: 49.99,
    discount: 0,
    stock: 42,
    rating: 4.5,
    numReviews: 388,
    tags: ["controller", "8bitdo", "retro", "bluetooth"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Versatile gamepad with pro-level paddle buttons, remappable controls and multi-platform support.",
    image: img("8BitDo Pro 2 Bluetooth Controller"),
    specs: {
      platform: "PC / Switch / Mobile",
      connectivity: "Bluetooth, 2.4G, USB-C",
      battery: "Built-in rechargeable",
      features: "Paddle buttons, turbo",
    },
  },

  // ——— Mouse Pad ———
  {
    name: "SteelSeries QcK Heavy XXL",
    category: "Mouse Pad",
    brand: "SteelSeries",
    price: 34.99,
    discount: 0,
    stock: 75,
    rating: 4.6,
    numReviews: 731,
    tags: ["mouse-pad", "steelseries", "cloth", "desk"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "Extra-thick cloth pad with a high-friction base that covers your whole desk.",
    image: img("SteelSeries QcK Heavy XXL"),
    specs: {
      size: "900x400x4mm",
      surface: "Micro-woven cloth",
      base: "Non-slip rubber",
      corner: "Stitched edges",
    },
  },
  {
    name: "Logitech G640 Cloth Game Pad",
    category: "Mouse Pad",
    brand: "Logitech",
    price: 24.99,
    discount: 0,
    stock: 60,
    rating: 4.4,
    numReviews: 429,
    tags: ["mouse-pad", "logitech", "cloth", "esports"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Consistent low-friction cloth surface trusted by pro esports players for tracking and flick shots.",
    image: img("Logitech G640 Cloth Game Pad"),
    specs: {
      size: "460x400x3mm",
      surface: "Low-friction cloth",
      base: "Rubber",
      corner: "Stitched edges",
    },
  },
  {
    name: "Razer Gigantus V2 Cloth Mouse Pad",
    category: "Mouse Pad",
    brand: "Razer",
    price: 19.99,
    discount: 10,
    stock: 70,
    rating: 4.3,
    numReviews: 356,
    tags: ["mouse-pad", "razer", "cloth", "control"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Anti-slip rubber base with a medium-friction cloth weave for controlled, precise aiming.",
    image: img("Razer Gigantus V2 Cloth Mouse Pad"),
    specs: {
      size: "450x400x3mm",
      surface: "Medium-friction cloth",
      base: "Anti-slip rubber",
      corner: "Stitched edges",
    },
  },
];

module.exports = { lifestyleProducts };