// Structured Computer Parts inventory for the Build Your PC configurator.
// Each part model's `specifications` map carries STRUCTURED compatibility
// fields (numbers + arrays) so the configurator can validate builds.
//
// Field conventions per category:
//   CPU         -> socket, tdp (W), cores, threads
//   Motherboard -> socket, ramType, ramSlots, formFactor
//   RAM         -> type, speed ("6000MT/s"), capacity
//   GPU         -> powerDraw (W), length_mm, pcieVersion
//   PSU         -> wattage
//   PC Case     -> formFactorSupport [array], maxGpuLength_mm
//   Cooling     -> socketSupport [array of compatible sockets]

const slugify = (name) =>
  name.toString().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)+/g, "");

const img = (name) => `/uploads/products/${slugify(name)}.jpg`;

const parts = [
  // ——— CPU ———
  {
    name: "AMD Ryzen 5 7600",
    category: "CPU",
    brand: "AMD",
    price: 229.99,
    discount: 0,
    stock: 40,
    rating: 4.8,
    numReviews: 642,
    tags: ["cpu", "amd", "am5", "zen4"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "6-core / 12-thread Zen 4 CPU with AM5 socket, 65W TDP and solid gaming performance.",
    image: img("AMD Ryzen 5 7600"),
    specifications: {
      socket: "AM5",
      tdp: 65,
      cores: 6,
      threads: 12,
      baseClock: "3.8GHz",
      boostClock: "5.1GHz",
      memoryType: "DDR5",
    },
  },
  {
    name: "AMD Ryzen 7 7800X3D",
    category: "CPU",
    brand: "AMD",
    price: 399.99,
    discount: 10,
    stock: 22,
    rating: 4.9,
    numReviews: 531,
    tags: ["cpu", "amd", "am5", "gaming", "3d-vcache"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "8-core Zen 4 CPU with 3D V-Cache for elite gaming performance on AM5.",
    image: img("AMD Ryzen 7 7800X3D"),
    specifications: {
      socket: "AM5",
      tdp: 120,
      cores: 8,
      threads: 16,
      baseClock: "4.2GHz",
      boostClock: "5.0GHz",
      cache: "96MB L3",
      memoryType: "DDR5",
    },
  },
  {
    name: "Intel Core i5-13600K",
    category: "CPU",
    brand: "Intel",
    price: 319.99,
    discount: 5,
    stock: 35,
    rating: 4.7,
    numReviews: 489,
    tags: ["cpu", "intel", "lga1700", "raptor-lake"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "14-core hybrid Raptor Lake CPU (6P+8E) for LGA1700 with strong multicore grunt.",
    image: img("Intel Core i5-13600K"),
    specifications: {
      socket: "LGA1700",
      tdp: 125,
      maxTdp: 181,
      cores: 14,
      threads: 20,
      baseClock: "3.5GHz",
      boostClock: "5.1GHz",
      memoryType: "DDR4 / DDR5",
    },
  },
  {
    name: "Intel Core i7-14700K",
    category: "CPU",
    brand: "Intel",
    price: 409.99,
    discount: 0,
    stock: 18,
    rating: 4.8,
    numReviews: 327,
    tags: ["cpu", "intel", "lga1700", "raptor-lake"],
    isFeatured: false,
    isTopSelling: true,
    description:
      "20-core hybrid Raptor Lake refresh (8P+12E) for LGA1700 — 28 threads of headroom.",
    image: img("Intel Core i7-14700K"),
    specifications: {
      socket: "LGA1700",
      tdp: 125,
      maxTdp: 253,
      cores: 20,
      threads: 28,
      baseClock: "3.4GHz",
      boostClock: "5.6GHz",
      memoryType: "DDR4 / DDR5",
    },
  },

  // ——— Motherboard ———
  {
    name: "ASUS ROG Strix B650E-F Gaming WiFi",
    category: "Motherboard",
    brand: "ASUS",
    price: 259.99,
    discount: 8,
    stock: 28,
    rating: 4.7,
    numReviews: 268,
    tags: ["motherboard", "asus", "am5", "atx", "ddr5"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "AM5 ATX board with DDR5, PCIe 5.0, WiFi 6E and premium ROG features.",
    image: img("ASUS ROG Strix B650E-F Gaming WiFi"),
    specifications: {
      socket: "AM5",
      ramType: "DDR5",
      ramSlots: 4,
      formFactor: "ATX",
      chipset: "B650E",
    },
  },
  {
    name: "MSI MAG B650 Tomahawk WiFi",
    category: "Motherboard",
    brand: "MSI",
    price: 219.99,
    discount: 0,
    stock: 32,
    rating: 4.6,
    numReviews: 314,
    tags: ["motherboard", "msi", "am5", "atx", "ddr5"],
    isFeatured: true,
    isTopSelling: false,
    description:
      "Reliable ATX AM5 motherboard with DDR5, PCIe 4.0 and built-in WiFi 6E.",
    image: img("MSI MAG B650 Tomahawk WiFi"),
    specifications: {
      socket: "AM5",
      ramType: "DDR5",
      ramSlots: 4,
      formFactor: "ATX",
      chipset: "B650",
    },
  },
  {
    name: "ASRock B650M PRO RS",
    category: "Motherboard",
    brand: "ASRock",
    price: 139.99,
    discount: 10,
    stock: 44,
    rating: 4.5,
    numReviews: 201,
    tags: ["motherboard", "asrock", "am5", "matx", "ddr5"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Budget AM5 micro-ATX board with DDR5 and PCIe 4.0 — great value builds.",
    image: img("ASRock B650M PRO RS"),
    specifications: {
      socket: "AM5",
      ramType: "DDR5",
      ramSlots: 4,
      formFactor: "mATX",
      chipset: "B650",
    },
  },
  {
    name: "Gigabyte Z790 Aorus Elite AX",
    category: "Motherboard",
    brand: "Gigabyte",
    price: 249.99,
    discount: 0,
    stock: 20,
    rating: 4.6,
    numReviews: 176,
    tags: ["motherboard", "gigabyte", "lga1700", "atx", "ddr5"],
    isFeatured: true,
    isTopSelling: false,
    description:
      "Intel Z790 ATX board with DDR5, PCIe 5.0 and WiFi 6E for 13th/14th gen CPU.",
    image: img("Gigabyte Z790 Aorus Elite AX"),
    specifications: {
      socket: "LGA1700",
      ramType: "DDR5",
      ramSlots: 4,
      formFactor: "ATX",
      chipset: "Z790",
    },
  },
  {
    name: "MSI MAG B760M Mortar WiFi",
    category: "Motherboard",
    brand: "MSI",
    price: 169.99,
    discount: 5,
    stock: 26,
    rating: 4.6,
    numReviews: 143,
    tags: ["motherboard", "msi", "lga1700", "matx", "ddr5"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Compact micro-ATX LGA1700 board with DDR5 and WiFi 6E.",
    image: img("MSI MAG B760M Mortar WiFi"),
    specifications: {
      socket: "LGA1700",
      ramType: "DDR5",
      ramSlots: 4,
      formFactor: "mATX",
      chipset: "B760",
    },
  },
  {
    name: "ASUS Prime B760M-A",
    category: "Motherboard",
    brand: "ASUS",
    price: 129.99,
    discount: 0,
    stock: 38,
    rating: 4.4,
    numReviews: 219,
    tags: ["motherboard", "asus", "lga1700", "matx", "ddr4"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Entry LGA1700 micro-ATX board with DDR4 — a home for budget Intel builds.",
    image: img("ASUS Prime B760M-A"),
    specifications: {
      socket: "LGA1700",
      ramType: "DDR4",
      ramSlots: 4,
      formFactor: "mATX",
      chipset: "B760",
    },
  },

  // ——— RAM ———
  {
    name: "Corsair Vengeance RGB 32GB (2x16GB) DDR5-6000",
    category: "RAM",
    brand: "Corsair",
    price: 104.99,
    discount: 15,
    stock: 60,
    rating: 4.8,
    numReviews: 784,
    tags: ["ram", "dram", "ddr5", "rgb", "32gb"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "32GB dual-channel DDR5-6000 kit with tight CL30 latency and striking RGB.",
    image: img("Corsair Vengeance RGB 32GB DDR5-6000"),
    specifications: {
      type: "DDR5",
      speed: "6000MT/s",
      latency: "CL30",
      capacity: "32GB (2x16GB)",
      modules: 2,
    },
  },
  {
    name: "G.Skill Trident Z5 32GB (2x16GB) DDR5-6400",
    category: "RAM",
    brand: "G.Skill",
    price: 129.99,
    discount: 0,
    stock: 34,
    rating: 4.7,
    numReviews: 412,
    tags: ["ram", "dram", "ddr5", "32gb"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "High-frequency DDR5-6400 kit tuned for top-tier Intel and AMD builds.",
    image: img("G.Skill Trident Z5 32GB DDR5-6400"),
    specifications: {
      type: "DDR5",
      speed: "6400MT/s",
      latency: "CL32",
      capacity: "32GB (2x16GB)",
      modules: 2,
    },
  },
  {
    name: "Kingston Fury Beast 16GB (2x8GB) DDR4-3600",
    category: "RAM",
    brand: "Kingston",
    price: 54.99,
    discount: 10,
    stock: 55,
    rating: 4.6,
    numReviews: 689,
    tags: ["ram", "dram", "ddr4", "16gb"],
    isFeatured: false,
    isTopSelling: true,
    description:
      "Affordable 16GB DDR4-3600 kit — the classic upgrade for DDR4 motherboards.",
    image: img("Kingston Fury Beast 16GB DDR4-3600"),
    specifications: {
      type: "DDR4",
      speed: "3600MT/s",
      latency: "CL17",
      capacity: "16GB (2x8GB)",
      modules: 2,
    },
  },
  {
    name: "TEAMGROUP T-Force Vulcan Z 32GB (2x16GB) DDR4-3600",
    category: "RAM",
    brand: "TEAMGROUP",
    price: 74.99,
    discount: 0,
    stock: 47,
    rating: 4.5,
    numReviews: 357,
    tags: ["ram", "dram", "ddr4", "32gb"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Dependable 32GB DDR4-3600 kit for high-core-count DDR4 systems.",
    image: img("TEAMGROUP T-Force Vulcan Z 32GB DDR4-3600"),
    specifications: {
      type: "DDR4",
      speed: "3600MT/s",
      latency: "CL18",
      capacity: "32GB (2x16GB)",
      modules: 2,
    },
  },

  // ——— GPU ———
  {
    name: "NVIDIA GeForce RTX 4070 Super",
    category: "GPU / Graphics Card",
    brand: "NVIDIA",
    price: 599.99,
    discount: 5,
    stock: 24,
    rating: 4.8,
    numReviews: 513,
    tags: ["gpu", "nvidia", "rtx", "4070", "4k"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "12GB RTX 40-series card with DLSS 3, 220W draw, and 267mm length.",
    image: img("NVIDIA GeForce RTX 4070 Super"),
    specifications: {
      powerDraw: 220,
      length_mm: 267,
      pcieVersion: "PCIe 4.0",
      memory: "12GB GDDR6X",
      recommendedPsu: 650,
    },
  },
  {
    name: "AMD Radeon RX 7800 XT",
    category: "GPU / Graphics Card",
    brand: "AMD",
    price: 499.99,
    discount: 8,
    stock: 30,
    rating: 4.7,
    numReviews: 388,
    tags: ["gpu", "amd", "radeon", "7800xt"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "16GB RDNA 3 card with FSR 3, 263W draw, and a wider 320mm cooler.",
    image: img("AMD Radeon RX 7800 XT"),
    specifications: {
      powerDraw: 263,
      length_mm: 320,
      pcieVersion: "PCIe 4.0",
      memory: "16GB GDDR6",
      recommendedPsu: 750,
    },
  },
  {
    name: "NVIDIA GeForce RTX 4090",
    category: "GPU / Graphics Card",
    brand: "NVIDIA",
    price: 1599.99,
    discount: 0,
    stock: 8,
    rating: 4.9,
    numReviews: 301,
    tags: ["gpu", "nvidia", "rtx", "4090", "flagship"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "Flagship 24GB GPU with massive 450W draw and long 336mm cooler.",
    image: img("NVIDIA GeForce RTX 4090"),
    specifications: {
      powerDraw: 450,
      length_mm: 336,
      pcieVersion: "PCIe 4.0",
      memory: "24GB GDDR6X",
      recommendedPsu: 850,
    },
  },

  // ——— PSU ———
  {
    name: "Corsair RM650x",
    category: "Power Supply",
    brand: "Corsair",
    price: 109.99,
    discount: 0,
    stock: 40,
    rating: 4.7,
    numReviews: 542,
    tags: ["psu", "power", "80plus-gold", "650w"],
    isFeatured: false,
    isTopSelling: true,
    description:
      "650W fully modular 80+ Gold PSU — plenty for mid-range builds.",
    image: img("Corsair RM650x"),
    specifications: {
      wattage: 650,
      rating: "80+ Gold",
      modularity: "Full",
    },
  },
  {
    name: "Seasonic Focus GX-750",
    category: "Power Supply",
    brand: "Seasonic",
    price: 139.99,
    discount: 5,
    stock: 26,
    rating: 4.8,
    numReviews: 467,
    tags: ["psu", "power", "80plus-gold", "750w"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "750W fully modular 80+ Gold PSU with 10-year guarantee.",
    image: img("Seasonic Focus GX-750"),
    specifications: {
      wattage: 750,
      rating: "80+ Gold",
      modularity: "Full",
    },
  },
  {
    name: "Corsair HX1000 Platinum",
    category: "Power Supply",
    brand: "Corsair",
    price: 249.99,
    discount: 0,
    stock: 14,
    rating: 4.8,
    numReviews: 233,
    tags: ["psu", "power", "platinum", "1000w"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "1000W fully modular 80+ Platinum PSU for flagship GPU lineups.",
    image: img("Corsair HX1000 Platinum"),
    specifications: {
      wattage: 1000,
      rating: "80+ Platinum",
      modularity: "Full",
    },
  },

  // ——— PC Case ———
  {
    name: "Fractal Design Meshify 2",
    category: "PC Case",
    brand: "Fractal Design",
    price: 159.99,
    discount: 10,
    stock: 21,
    rating: 4.8,
    numReviews: 378,
    tags: ["case", "fractal", "atx", "airflow"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "Roomy ATX mid-tower with great airflow and 467mm GPU clearance.",
    image: img("Fractal Design Meshify 2"),
    specifications: {
      formFactorSupport: ["ATX", "mATX", "ITX"],
      maxGpuLength_mm: 467,
    },
  },
  {
    name: "NZXT H5 Flow",
    category: "PC Case",
    brand: "NZXT",
    price: 89.99,
    discount: 0,
    stock: 38,
    rating: 4.6,
    numReviews: 412,
    tags: ["case", "nzxt", "atx", "airflow"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "Sleek ATX mid-tower with dual 140mm airflow intake and 365mm GPU support.",
    image: img("NZXT H5 Flow"),
    specifications: {
      formFactorSupport: ["ATX", "mATX", "ITX"],
      maxGpuLength_mm: 365,
    },
  },
  {
    name: "Cooler Master NR200P",
    category: "PC Case",
    brand: "Cooler Master",
    price: 99.99,
    discount: 0,
    stock: 16,
    rating: 4.5,
    numReviews: 266,
    tags: ["case", "cooler-master", "itx", "sff"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Compact SFF case supporting mATX/ITX boards with a 330mm GPU limit.",
    image: img("Cooler Master NR200P"),
    specifications: {
      formFactorSupport: ["mATX", "ITX"],
      maxGpuLength_mm: 330,
    },
  },

  // ——— Cooling ———
  {
    name: "Noctua NH-U12S chromax.black",
    category: "Cooling",
    brand: "Noctua",
    price: 89.99,
    discount: 0,
    stock: 30,
    rating: 4.8,
    numReviews: 356,
    tags: ["cooling", "air", "noctua"],
    isFeatured: true,
    isTopSelling: true,
    description:
      "Legendary single-tower air cooler in all-black finish, 120mm.",
    image: img("Noctua NH-U12S chromax.black"),
    specifications: {
      socketSupport: ["AM5", "LGA1700", "LGA1200"],
      type: "Air",
      fanSize: "120mm",
    },
  },
  {
    name: "Cooler Master Hyper 212 Halo",
    category: "Cooling",
    brand: "Cooler Master",
    price: 44.99,
    discount: 5,
    stock: 52,
    rating: 4.5,
    numReviews: 689,
    tags: ["cooling", "air", "budget"],
    isFeatured: false,
    isTopSelling: true,
    description:
      "The classic budget air cooler with a halo fan ring and black pipes.",
    image: img("Cooler Master Hyper 212 Halo"),
    specifications: {
      socketSupport: ["AM5", "LGA1700", "LGA1200"],
      type: "Air",
      fanSize: "120mm",
    },
  },
  {
    name: "Corsair iCUE H150i Elite",
    category: "Cooling",
    brand: "Corsair",
    price: 179.99,
    discount: 10,
    stock: 17,
    rating: 4.7,
    numReviews: 314,
    tags: ["cooling", "aio", "liquid", "360mm"],
    isFeatured: true,
    isTopSelling: false,
    description:
      "360mm all-in-one liquid cooler with a bright LCD pump head.",
    image: img("Corsair iCUE H150i Elite"),
    specifications: {
      socketSupport: ["AM5", "LGA1700", "LGA1200"],
      type: "AIO Liquid",
      fanSize: "360mm",
    },
  },
  {
    name: "Noctua NH-U9S",
    category: "Cooling",
    brand: "Noctua",
    price: 99.99,
    discount: 0,
    stock: 9,
    rating: 4.6,
    numReviews: 178,
    tags: ["cooling", "air", "noctua", "sff"],
    isFeatured: false,
    isTopSelling: false,
    description:
      "Dual-fan SFF air cooler with older-socket focus (AM4 / LGA1200).",
    image: img("Noctua NH-U9S"),
    specifications: {
      socketSupport: ["AM4", "LGA1200"],
      type: "Air",
      fanSize: "92mm",
    },
  },
];

module.exports = { parts, img, slugify };